Wrap fun and with-gensyms with eval-when
zkat/chanl pull request #22
Opened 2021-03-12 16:55 UTC by desiderius

This simple fix allow `chanl` to be buill with Allegro CL.

2021-03-13 22:45 UTC, adlai commented
Thank you for the suggestion; please post the failure that makes this necessary.

2021-03-15 12:07 UTC, desiderius commented
```common lisp
(ql:quickload "chanl")
```
```
attempt to call `chanl::fun' which is an undefined function.
```

when compiling `utils.lisp`.

2021-03-15 21:23 UTC, adlai commented on src/utils.lisp
> +(eval-when (:compile-toplevel :load-toplevel :execute)
eval-always is never a good idea, so I prefer PRs with as few of these as possible.

2021-03-15 21:24 UTC, adlai requested changes
lift econd to minimize count of eval-always forms

2021-03-17 16:08 UTC, merged

2021-03-18 11:13 UTC, desiderius commented
Sorry, I missed the change request. Thank you for your time.